services:
  - type: web
    name: multimodal-fake-news
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
